services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
          $extension: '@Zikula\PageLockModule\ZikulaPageLockModule'

    Zikula\PageLockModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\PageLockModule\Api\ApiInterface\LockingApiInterface: '@Zikula\PageLockModule\Api\LockingApi'

    Zikula\PageLockModule\Api\LockingApi:
        arguments:
          $footerAssetBag: '@zikula_core.common.theme.assets_footer'
          $tempDir: '%kernel.cache_dir%'
